import argparse
import importlib.util
import pathlib
import re
import textwrap

parser = argparse.ArgumentParser()
parser.add_argument("path")
args = parser.parse_args()

dvc = pathlib.Path(args.path)

spec = importlib.util.spec_from_file_location(
    "dvc.version", dvc / "version.py",
)
dvc_version = importlib.util.module_from_spec(spec)
spec.loader.exec_module(dvc_version)
version = dvc_version.__version__

(dvc / "version.py").write_text(
    textwrap.dedent(
        f"""\
        # AUTOGENERATED at build time by iterative/dvc-snap
        __version__ = "{version}"
    """
    )
)

(dvc / "utils" / "build.py").write_text('PKG = "snap"')

# dvc = pathlib.Path("/home/cc16/gits/iterative/dvc")
setup = (dvc.parent / "setup.cfg").read_text()
# TODO: hdfs oss ssh webdav
extras = ")s\n    %(".join("azure gdrive gs ssh s3".split())
setup = re.sub(r"^(install_requires\s?=)$", "\\1\n    %(" + extras + ")s", setup, flags=re.M)
(dvc.parent / "setup.cfg").write_text(setup)
