name: dvc
summary: Data Version Control
description: Git for Data & Models https://dvc.org
version: "2.0.17"
confinement: classic
grade: stable
base: core18
apps:
  dvc:
    command: bin/dvc
parts:
  dvc:
    plugin: python
    source: https://github.com/iterative/dvc.git
