name: dvc
summary: Data Version Control
description: Git for Data & Models https://dvc.org
version: 3.44.0
confinement: classic
grade: stable
base: core22
license: Apache-2.0
layout:
  /etc/dvc:
    bind: $SNAP_DATA/etc/dvc
  /etc/hadoop:
    bind: $SNAP_DATA/etc/hadoop
apps:
  dvc:
    command: bin/python3 $SNAP/bin/dvc
    completer: completion.sh
    environment:
      XDG_CONFIG_DIRS: /etc
      JAVA_HOME: "$SNAP/java-se-7u75-ri"
      HADOOP_HOME: "$SNAP/hadoop-2.7.2"
      CLASSPATH: "$($HADOOP_HOME/bin/hdfs classpath --glob)"
      PATH: "/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$SNAP/usr/bin:$SNAP/bin:$HADOOP_HOME/sbin:$HADOOP_HOME/bin:$PATH"
parts:
  dvc:
    plugin: python
    source: https://github.com/iterative/dvc.git
    source-tag: 3.44.0
    build-packages:
    - git
    - libc-dev
    stage-packages:
    - git
    - libpython3-stdlib
    - libpython3.10-stdlib
    - libpython3.10-minimal
    - python3-pip
    - python3-setuptools
    - python3-wheel
    - python3-venv
    - python3-minimal
    - python3-distutils
    - python3-pkg-resources
    - python3.10-minimal
    override-pull: |
        craftctl default
        git diff --quiet || error_dirty_build
        echo 'PKG = "snap"' > dvc/_build.py
    override-build: |
        craftctl default
        $PARTS_PYTHON_INTERPRETER -m pip install -U pip setuptools_scm build
        $PARTS_PYTHON_INTERPRETER -m pip install -U .[all]
        $PARTS_PYTHON_INTERPRETER -m dvc --version
        $PARTS_PYTHON_INTERPRETER -m dvc completion -s bash > $CRAFT_PART_INSTALL/completion.sh
