name: dvc
summary: Data Version Control
description: Git for Data & Models https://dvc.org
version: 3.63.0
confinement: classic
grade: stable
base: core20
license: Apache-2.0
layout:
  /etc/dvc:
    bind: $SNAP_DATA/etc/dvc
  /etc/hadoop:
    bind: $SNAP_DATA/etc/hadoop
apps:
  dvc:
    command: bin/python3 $SNAP/bin/dvc
    completer: completion.sh
    environment:
      XDG_CONFIG_DIRS: /etc
      JAVA_HOME: "$SNAP/java-se-7u75-ri"
      HADOOP_HOME: "$SNAP/hadoop-2.7.2"
      CLASSPATH: "$($HADOOP_HOME/bin/hdfs classpath --glob)"
      PATH: "/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$SNAP/usr/bin:$SNAP/bin:$HADOOP_HOME/sbin:$HADOOP_HOME/bin:$PATH"
package-repositories:
 - type: apt
   ppa: deadsnakes/ppa
 - type: apt
   ppa: git-core/ppa
parts:
  dvc-libs:
    plugin: nil
    build-packages:
    - curl
    - tar
    - gzip
    stage-packages:
    - git
    - python3.12
    - python3.12-venv
    override-build: |
        snapcraftctl build
  dvc:
    after: [dvc-libs]
    plugin: python
    source: https://github.com/iterative/dvc.git
    source-tag: 3.63.0
    build-environment:
      - SNAPCRAFT_PYTHON_INTERPRETER: python3.12
    build-packages:
    - git
    - libc-dev
    override-pull: |
        snapcraftctl pull
        git diff --quiet || error_dirty_build
        $SNAP/usr/bin/python3 --version
        echo 'PKG = "snap"' > dvc/_build.py
    override-build: |
        snapcraftctl build
        $SNAPCRAFT_PART_INSTALL/bin/python3 -m pip install -U .[all]
        $SNAPCRAFT_PART_INSTALL/bin/python3 -m dvc --version
        find "${SNAPCRAFT_PART_INSTALL}" -type f -executable -print0 | xargs -0 sed -i "1 s|^#\\!${SNAPCRAFT_PART_INSTALL}/bin/python3.*$|#\\!/usr/bin/env python3|"
        $SNAPCRAFT_PART_INSTALL/bin/python3 -m dvc completion -s bash > $SNAPCRAFT_PART_INSTALL/completion.sh
        # python3 fixup symlink (snapcraft bug)
        ln -sf ../usr/bin/python3.12 $SNAPCRAFT_PART_INSTALL/bin/python3
        ln -sf ../usr/bin/python3.12 $SNAPCRAFT_PART_INSTALL/bin/python
        ln -sf ../usr/bin/python3.12 $SNAPCRAFT_PART_INSTALL/bin/python3.12
        # https://forum.snapcraft.io/t/upgrading-classic-snap-to-core24-using-snapcraft-8-3-causes-python-3-12-errors-at-runtime/41045/11
        cat "${SNAPCRAFT_PART_INSTALL}/pyvenv.cfg"
        sed -i "${SNAPCRAFT_PART_INSTALL}/pyvenv.cfg" -e 's@^home = '"${SNAPCRAFT_STAGE}"'/usr/bin$@home = /snap/dvc/current/usr/bin@g'
        cat "${SNAPCRAFT_PART_INSTALL}/pyvenv.cfg"
