name: dvc
summary: Data Version Control
description: Git for Data & Models https://dvc.org
version: 3.64.1
confinement: classic
grade: stable
base: core24
license: Apache-2.0
layout:
  /etc/dvc:
    bind: $SNAP_DATA/etc/dvc
  /etc/hadoop:
    bind: $SNAP_DATA/etc/hadoop
platforms:
  amd64:
  arm64:
apps:
  dvc:
    command: bin/python3 $SNAP/bin/dvc
    completer: completion.sh
    environment:
      XDG_CONFIG_DIRS: /etc
      JAVA_HOME: "$SNAP/java-se-7u75-ri"
      HADOOP_HOME: "$SNAP/hadoop-2.7.2"
      CLASSPATH: "$($HADOOP_HOME/bin/hdfs classpath --glob)"
      PATH: "/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$SNAP/usr/bin:$SNAP/bin:$HADOOP_HOME/sbin:$HADOOP_HOME/bin:$PATH"
package-repositories:
 - type: apt
   ppa: deadsnakes/ppa
parts:
  dvc:
    plugin: python
    source: https://github.com/iterative/dvc.git
    source-tag: 3.64.1
    build-packages:
    - git
    stage-packages:
    - git
    - python3.14
    - python3.14-venv
    build-environment:
    - PARTS_PYTHON_INTERPRETER: python3.14
    python-packages:
    - ".[all]"
    override-pull: |
        craftctl default
        git diff --quiet || error_dirty_build
        echo 'PKG = "snap"' > dvc/_build.py
    override-build: |
        craftctl default
        $PARTS_PYTHON_INTERPRETER -m dvc --version
        $PARTS_PYTHON_INTERPRETER -m dvc completion -s bash > $CRAFT_PART_INSTALL/completion.sh
    build-attributes:
    - enable-patchelf
