name: dvc
summary: Data Version Control
description: Git for Data & Models https://dvc.org
version: "2.0.17"
confinement: classic
grade: stable
license: Apache-2.0
apps:
  aws:
    # Workaround https://bugs.launchpad.net/snappy/+bug/1664427
    command: usr/bin/python3 $SNAP/bin/dvc
    aliases: [dvc]
parts:
  aws:
    plugin: python
    source: https://github.com/iterative/dvc.git
