name: dvc
summary: Data Version Control
description: Git for Data & Models https://dvc.org
version: 3.44.0
confinement: classic
grade: stable
base: core22
license: Apache-2.0
layout:
  /etc/dvc:
    bind: $SNAP_DATA/etc/dvc
apps:
  dvc:
    command: usr/bin/dvc
    completer: completion.sh
    environment:
      XDG_CONFIG_DIRS: /etc
parts:
  dvc:
    plugin: python
    source: https://github.com/iterative/dvc.git
    source-tag: 3.44.0
    python-packages:
    - pip
    - setuptools
    - wheel
    - .[all]
    build-attributes:
    - enable-patchelf
    stage-packages:
    - git
    - libpython3-stdlib
    - libpython3.10-stdlib
    - libpython3.10-minimal
    - python3-pip
    - python3-setuptools
    - python3-wheel
    - python3-venv
    - python3-minimal
    - python3-distutils
    - python3-pkg-resources
    - python3.10-minimal
      #    override-pull: |
      #        craftctl default
      #        git diff --quiet || error_dirty_build
      #        echo 'PKG = "snap"' > dvc/_build.py
      #    override-build: |
      #        craftctl default
      #        $PARTS_PYTHON_INTERPRETER -m dvc completion -s bash > $CRAFT_PART_INSTALL/completion.sh
      #        find "${CRAFT_STAGE}/bin" -type f -executable -exec sed -i 's/!\/usr\/bin\/env python3.12/!\/usr\/bin\/env python3/' {} \;
      #        sed -i 's/include-system-site-packages = false/include-system-site-packages = true/g' "${CRAFT_STAGE}/pyvenv.cfg" 
