name: dvc
summary: Data Version Control
description: Git for Data & Models https://dvc.org
adopt-info: dvc
confinement: classic
grade: stable
base: core18
license: Apache-2.0
layout:
  /etc/dvc:
    bind: $SNAP_DATA/etc/dvc
apps:
  dvc:
    command: bin/dvc
    completer: completion.sh
    environment:
      XDG_CONFIG_DIRS: /etc
parts:
  dvc:
    plugin: python
    source: https://github.com/iterative/dvc.git
    source-tag: 2.7.4
    build-snaps:
    - snapd
    build-packages:
    - git
    - libc-dev
    stage-packages:
    - git
    override-pull: |
        snapcraftctl pull
        git diff --quiet || error_dirty_build
        $SNAP/usr/bin/python3 --version
        $SNAP/usr/bin/python3 $SNAPCRAFT_PROJECT_DIR/freeze.py $(pwd)/dvc
        # install all optional extras
        sed -ri 's/(install_requires=install_requires)/\1+requirements["all"]/' setup.py
    override-build: |
        snapcraftctl build
        # prevent user site packages interfering with this snap - reference:
        # https://github.com/snapcore/snapcraft/blob/19393ef36cd773a28131cec10cc0bfb3bf9c7e77/tools/snapcraft-override-build.sh#L18
        sed -ri 's/^(ENABLE_USER_SITE = )None$/\1False/' $SNAPCRAFT_PART_INSTALL/usr/lib/python*/site.py
        # make plugin aware that a file (generated later) needs to be staged
        touch $SNAPCRAFT_PART_INSTALL/completion.sh
    override-stage: |
        snapcraftctl stage
        snapcraftctl set-version $(usr/bin/python3 -m dvc --version)
        usr/bin/python3 -m dvc completion -s bash > completion.sh
