name: Build package
on: [push, pull_request]
jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: snapcraft
    - name: Test the package
      run: |
        sudo snap install --dangerous --classic ${{ steps.snapcraft.outputs.snap }}
        dvc doctor
        dvc doctor | grep "azure\|gdrive\|gs\|s3\|webdav"
        dvc list https://github.com/iterative/dvc
        dvc get https://github.com/iterative/dataset-registry get-started/data.xml -o data.xml
        sudo snap remove dvc
    - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: stable,v2/stable
