name: Build package
on: [push, pull_request]
jobs:
  snap:
    runs-on: ubuntu-20.04  # https://github.com/snapcore/action-build/issues/42
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: snapcraft
    - name: Test the package
      run: |
        sudo snap install --dangerous --classic ${{ steps.snapcraft.outputs.snap }}
        dvc doctor
        dvc doctor | grep "azure\|gdrive\|gs\|s3\|webdav"
        dvc list https://github.com/iterative/dvc
        dvc get https://github.com/iterative/dataset-registry get-started/data.xml -o data.xml
        sudo snap remove dvc
    - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: stable,v2/stable

  notify:
    if: github.ref == 'refs/heads/main' && failure()
    needs: [snap]
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.3.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'Package build failed for ${{ github.repository }}'
        SLACK_TITLE: CI Status
        SLACK_USERNAME: dvc-pkg-build
