name: Update package
on:
  schedule:
  - cron: '0 0 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get latest dvc version
      id: latest
      run: |
        version=$(./latest.sh)
        echo "::set-output name=version::$version"
    - name: try update
      id: update
      run: |
        echo latest version ${{ steps.latest.outputs.version }}
        ./update.sh ${{ steps.latest.outputs.version }}
        echo "::set-output name=changes::$(git diff)"
    - name: create PR
      if: ${{ steps.update.outputs.changes != '' }}
      run: |
        git config --global user.name "Olivaw[bot]"
        git config --global user.email "64868532+iterative-olivaw@users.noreply.github.com"
        git commit -am "dvc ${{ steps.latest.outputs.version }}"
        gh pr create --title "dvc ${{ steps.latest.outputs.version }}"
